### ISSUE TITLE
Preconfigure Gogs using ConfigMap

### ISSUE THREAD

**Issue by siamaksade** [OpenShiftDemos/openshift-cd-demo#1]
Use ConfigMap to mount custom database configuration to _custom/conf/app.ini_ so that Gogs is pre-configured when template is instantiated.

**Comment by thoraxe** [comment]
preconfiguration of gogs won't work because it needs to initialize the database.

However, if you want to change the title of this issue, I think we can use curl+POST as a post-deployment hook to call the installation of Gogs.
