### ISSUE TITLE
Nexus and SonarQube containers won't start

### ISSUE THREAD

**Issue by mphmelsen** [OpenShiftDemos/openshift-cd-demo#16]
I've tried both templates (github and gogs) to setup the cicd environment. Unfortunately the nexus and sonarqube services fail as the deployments fail. The nexus deployment comes with the following log:

`I0805 07:18:29.020785       1 deployer.go:200] Deploying cicd/nexus-4 for the first time (replicas: 1)
I0805 07:18:29.024570       1 recreate.go:126] Scaling cicd/nexus-4 to 1 before performing acceptance check
I0805 07:18:31.057037       1 recreate.go:131] Performing acceptance check of cicd/nexus-4
I0805 07:18:31.057124       1 lifecycle.go:445] Waiting 600 seconds for pods owned by deployment "cicd/nexus-4" to become ready (checking every 1 seconds; 0 pods previously accepted)
F0805 07:28:31.057644 1 deployer.go:70] update acceptor rejected cicd/nexus-4: pods for deployment "cicd/nexus-4" took longer than 600 seconds to become ready `

and the sonarqube comes with:

`I0805 07:26:12.470246       1 deployer.go:200] Deploying cicd/sonarqube-3 for the first time (replicas: 1)
I0805 07:26:12.475621       1 recreate.go:126] Scaling cicd/sonarqube-3 to 1 before performing acceptance check
I0805 07:26:14.530304       1 recreate.go:131] Performing acceptance check of cicd/sonarqube-3
I0805 07:26:14.530378       1 lifecycle.go:445] Waiting 600 seconds for pods owned by deployment "cicd/sonarqube-3" to become ready (checking every 1 seconds; 0 pods previously accepted)
F0805 07:36:14.530993 1 deployer.go:70] update acceptor rejected cicd/sonarqube-3: pods for deployment "cicd/sonarqube-3" took longer than 600 seconds to become ready`

oc get pods shows

`jdk-jenkins-slave-1-build      0/1       Completed          0          2h
jenkins-1-build                0/1       Completed          0          2h
jenkins-1-wv5b0                1/1       Running            0          2h
nexus-1-deploy                 0/1       DeadlineExceeded   0          2h
nexus-2-deploy                 0/1       DeadlineExceeded   0          2h
nexus-3-deploy                 0/1       DeadlineExceeded   0          2h
nexus-4-deploy                 0/1       Error              0          35m
postgresql-sonarqube-1-2oe3z   1/1       Running            0          2h
sonarqube-1-deploy             0/1       DeadlineExceeded   0          2h
sonarqube-2-deploy             0/1       Error              0          2h
sonarqube-3-deploy             0/1       Error              0          27m`

any idea why this doesn't work?

**Comment by jaenswart** [comment]
Hi, what was the outcome of this? What is needed to get past the 600 sec delay and failed for jenkins

**Comment by ostests** [comment]
I have the same situation. How to solve this issue?

**Comment by cambiph** [comment]
Same here for Jenkins

**Comment by mphmelsen** [comment]
in my case the problem was due to little resources were assigned by vagrant to my cdk setup. I had only 1gb of memory and this setup needs at least 4 (from the top of my head). after upgrading the memory settings, things started working smoothly

**Comment by siamaksade** [comment]
That sounds correct. As mentioned in [README.md](https://github.com/OpenShiftDemos/openshift-cd-demo/blob/openshift-3.3/README.md#setup), this demo requires at least 6 GB memory for the containers. You'd need some more for the vagrant box as well.

**Comment by cambiph** [comment]
So it cannot be deployed on the developer preview since it only gives 2GB of memory?

**Comment by siamaksade** [comment]
Not currently. You need three projects for this demo to model various environments. Dev Preview gives you only one at the moment.

**Comment by saurabhtandon13** [comment]
Memory cant be only reason of this failure, if my internet is running slow and it takes time to download the image then the deployment will also get failed. Now here question is how to increase the deployment configuration time from 10m to say 20m.

**Comment by sanjusoftware** [comment]
wondering why is this issue closed while it still has open questions!! I am also facing the same errors as mentioned above and not sure how to get around it. any pointers?

**Comment by siamaksade** [comment]
@saurabhtandon13 increasing the timeout does not solve that issue in a generic way. There is always a slower internet than the one you test with

@sanjusoftware on which OpenShift cluster and what version do you deploy this demo?

**Comment by saurabhtandon13** [comment]
Hello Sanju, 

i am using the OCP 3.3 ...
