### ISSUE TITLE
stage project is unable to pull image from dev

### ISSUE THREAD

**Issue by VeerMuchandi** [OpenShiftDemos/openshift-cd-demo#19]
oc policy add-role-to-group system:image-puller system:serviceaccounts:stage -n dev
Without the above the stage project is unable to pull image from dev

**Comment by siamaksade** [comment]
The edit role on the serviceaccount should allow stage project to pull from dev as mentioned in the README:

```
oc policy add-role-to-user edit system:serviceaccount:cicd:default -n dev
```
